<?php

namespace App\Console\Commands;

use App\Enums\Activity;
use App\Enums\Stage;
use App\Models\Exercise;
use Illuminate\Console\Command;

/**
 * Bakes the warm-up exercise data and engine config into a JS module
 * (resources/js/data/warmup-data.js) so the routine builder can run fully
 * client-side and offline. Re-run after editing exercises or config:
 *
 *     php artisan warmup:export-js
 */
class ExportWarmupData extends Command
{
    protected $signature = 'warmup:export-js';

    protected $description = 'Export warm-up exercises + config to resources/js/data/warmup-data.js for offline use';

    public function handle(): int
    {
        $exercises = Exercise::with('tags')->warmups()->ordered()->get()
            ->mapWithKeys(fn (Exercise $e) => [$e->slug => [
                ...$e->toClientArray(),
                'min_level' => $e->min_level,
                'min_intensity' => $e->min_intensity->value,
                'elastic' => $e->elastic,
                'equipment' => $e->equipment ?? [],
                'seconds' => $e->seconds,
                'cues' => $e->cues,
            ]])
            ->all();

        $splits = collect(Activity::cases())
            ->mapWithKeys(fn (Activity $a) => [$a->value => [
                'short' => $a->shortLabel(),
                'emoji' => $a->emoji(),
                'muscles' => $a->muscles(),
            ]])
            ->all();

        $stages = collect(Stage::cases())
            ->map(fn (Stage $s) => [
                'key' => $s->value,
                'number' => $s->number(),
                'label' => $s->label(),
                'description' => $s->description(),
            ])
            ->all();

        $warmup = config('warmup');

        $data = [
            'exercises' => $exercises,
            'splits' => $splits,
            'stages' => $stages,
            'levels' => [1 => 'Re-entry', 2 => 'Conditioning', 3 => 'Performance Preparation'],
            'config' => [
                'durations' => $warmup['durations'],
                'transition_seconds' => $warmup['transition_seconds'],
                'stage_budgets' => $warmup['stage_budgets'],
                'budget_shift' => $warmup['budget_shift'],
                'equipment' => $warmup['equipment'],
                'default_equipment' => $warmup['default_equipment'],
                'quick' => $warmup['quick'],
                'templates' => $warmup['templates'],
            ],
        ];

        $json = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);

        $header = "/* AUTO-GENERATED by `php artisan warmup:export-js` — do not edit by hand.\n".
            "   Bakes warm-up exercises + engine config into the JS bundle so the\n".
            "   routine builder runs fully client-side (offline). */\n\n";

        $path = resource_path('js/data/warmup-data.js');
        if (! is_dir(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }
        file_put_contents($path, $header.'export const DATA = '.$json.";\n");

        $this->info('Wrote '.count($exercises).' warm-up exercises to '.str_replace(base_path().'/', '', $path));

        return self::SUCCESS;
    }
}
